Fix Home Manager switch to include Git-ignored file `customization.nix`
Otherwise, there are now errors like this:

> error: path '/nix/store/…-source/customization.nix' does not exist

See also:

- https://github.com/NixOS/nix/issues/6642
- https://github.com/NixOS/nix/issues/7107